
services:

    postgres:
        build:
            context: ${SRC_PATH}/.
            dockerfile: Dockerfile
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASS}
            - POSTGRES_DB=${DB_NAME}
        ports:
            - "5432:5432"
        volumes:
            - ./data/postgresql:/var/lib/postgresql/data
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql

